import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import { useAppSelector } from "../src/hooks/redux-hooks";
const Home: NextPage = () => {
  const { userDetails } = useAppSelector((state) => state.userReducer);
  console.log(userDetails);

  return (
    <React.Fragment>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="page-wrapper">
          {/* <!-- Hero section--> */}
          <section
            className="bg-accent bg-position-top-center bg-repeat-0 py-5"
            style={{ backgroundImage: "url(img/home/marketplace-hero.jpg)" }}
          >
            <div className="pb-lg-5 mb-lg-3">
              <div className="container py-lg-5 my-lg-5">
                <div className="row mb-4 mb-sm-5">
                  <div className="col-lg-7 col-md-9 text-center text-sm-start">
                    <h1 className="text-white lh-base">
                      <span className="fw-light">Over</span> 1,500{" "}
                      <span className="fw-light">curated</span> Design{" "}
                      <span className="fw-light">resources</span>, Images,
                      Graphic <span className="fw-light">&amp;</span> Website{" "}
                      <span className="fw-light">templates</span>
                    </h1>
                    <h2 className="h5 text-white fw-light">
                      High quality items created by our global community
                    </h2>
                  </div>
                </div>
                <div className="row pb-lg-5 mb-4 mb-sm-5">
                  <div className="col-lg-6 col-md-8">
                    <div className="input-group input-group-lg flex-nowrap">
                      <i className="ci-search position-absolute top-50 translate-middle-y ms-3"></i>
                      <input
                        className="form-control rounded-start"
                        type="text"
                        placeholder="Start your search"
                      />
                      <button
                        className="btn btn-primary btn-lg dropdown-toggle fs-base"
                        type="button"
                        data-bs-toggle="dropdown"
                      >
                        All categories
                      </button>
                      <div className="dropdown-menu dropdown-menu-end my-1">
                        <a className="dropdown-item" href="#">
                          Photos
                        </a>
                        <a className="dropdown-item" href="#">
                          Graphics
                        </a>
                        <a className="dropdown-item" href="#">
                          UI Design
                        </a>
                        <a className="dropdown-item" href="#">
                          Web Themes
                        </a>
                        <a className="dropdown-item" href="#">
                          Add-Ons
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* <!-- Trending products (Carousel)--> */}
          <section className="container pt-md-3 pb-5 mb-md-3">
            <h2 className="h3 text-center">Trending products</h2>
            <div className="row pt-4 mx-n2">
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-4">
                <div className="card product-card">
                  <button
                    className="btn-wishlist btn-sm"
                    type="button"
                    data-bs-toggle="tooltip"
                    data-bs-placement="left"
                    title="Add to wishlist"
                  >
                    <i className="ci-heart"></i>
                  </button>
                  <a
                    className="card-img-top d-block overflow-hidden"
                    href="shop-single-v1.html"
                  >
                    <img src="/img/23.jpg" alt="Product" />
                  </a>
                  <div className="card-body py-2">
                    <a className="product-meta d-block fs-xs pb-1" href="#">
                      Women's Sneakers
                    </a>
                    <h3 className="product-title fs-sm">
                      <a href="shop-single-v1.html">
                        Leather High-Top Sneakers
                      </a>
                    </h3>
                    <div className="d-flex justify-content-between">
                      <div className="product-price">
                        <span className="text-accent">
                          $215.<small>00</small>
                        </span>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star"></i>
                      </div>
                    </div>
                  </div>
                  <div className="card-body card-body-hidden">
                    <div className="text-center pb-2">
                      <div className="form-check form-option form-check-inline mb-2">
                        <input
                          className="form-check-input"
                          type="radio"
                          name="size5"
                          id="s4-80"
                        />
                        <label className="form-option-label" htmlFor="s4-80">
                          8
                        </label>
                      </div>
                      <div className="form-check form-option form-check-inline mb-2">
                        <input
                          className="form-check-input"
                          type="radio"
                          name="size5"
                          id="s4-85"
                          checked
                        />
                        <label className="form-option-label" htmlFor="s4-85">
                          8.5
                        </label>
                      </div>
                      <div className="form-check form-option form-check-inline mb-2">
                        <input
                          className="form-check-input"
                          type="radio"
                          name="size5"
                          id="s4-90"
                        />
                        <label className="form-option-label" htmlFor="s4-90">
                          9
                        </label>
                      </div>
                      <div className="form-check form-option form-check-inline mb-2">
                        <input
                          className="form-check-input"
                          type="radio"
                          name="size5"
                          id="s4-95"
                        />
                        <label className="form-option-label" htmlFor="s4-95">
                          9.5
                        </label>
                      </div>
                    </div>
                    <button
                      className="btn btn-primary btn-sm d-block w-100 mb-2"
                      type="button"
                    >
                      <i className="ci-cart fs-sm me-1"></i>Add to Cart
                    </button>
                    <div className="text-center">
                      <a
                        className="nav-link-style fs-ms"
                        href="#quick-view"
                        data-bs-toggle="modal"
                      >
                        <i className="ci-eye align-middle me-1"></i>Quick view
                      </a>
                    </div>
                  </div>
                </div>
                <hr className="d-sm-none" />
              </div>
            </div>
            <div className="text-center pt-3">
              <a className="btn btn-outline-accent" href="shop-grid-ls.html">
                More products<i className="ci-arrow-right ms-1"></i>
              </a>
            </div>
          </section>
          {/* <!-- Marketplace features--> */}
          <section
            className="bg-accent bg-size-cover bg-position-center pt-5 pb-4 pb-lg-5"
            style={{
              backgroundImage: "url(img/marketplace/features/features-bg.jpg)",
            }}
          >
            <div className="container pt-lg-3">
              <h2 className="h3 mb-3 pb-4 text-light text-center">
                Why our marketplace?
              </h2>
              <div className="row pt-lg-2 text-center">
                <div className="col-lg-3 col-sm-6 mb-grid-gutter">
                  <div className="d-inline-flex align-items-center text-start">
                    <img
                      src="img/marketplace/features/quality.png"
                      width="52"
                      alt="Quality Guarantee"
                    />
                    <div className="ps-3">
                      <h6 className="text-light fs-base mb-1">
                        Quality Guarantee
                      </h6>
                      <p className="text-light fs-ms opacity-70 mb-0">
                        Quality checked by our team
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-lg-3 col-sm-6 mb-grid-gutter">
                  <div className="d-inline-flex align-items-center text-start">
                    <img
                      src="img/marketplace/features/support.png"
                      width="52"
                      alt="Customer Support"
                    />
                    <div className="ps-3">
                      <h6 className="text-light fs-base mb-1">
                        Customer Support
                      </h6>
                      <p className="text-light fs-ms opacity-70 mb-0">
                        Friendly 24/7 customer support
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-lg-3 col-sm-6 mb-grid-gutter">
                  <div className="d-inline-flex align-items-center text-start">
                    <img
                      src="img/marketplace/features/updates.png"
                      width="52"
                      alt="Free Updates"
                    />
                    <div className="ps-3">
                      <h6 className="text-light fs-base mb-1">
                        Lifetime Free Updates
                      </h6>
                      <p className="text-light fs-ms opacity-70 mb-0">
                        Never pay for an update
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-lg-3 col-sm-6 mb-grid-gutter">
                  <div className="d-inline-flex align-items-center text-start">
                    <img
                      src="img/marketplace/features/secure.png"
                      width="52"
                      alt="Secure Payments"
                    />
                    <div className="ps-3">
                      <h6 className="text-light fs-base mb-1">
                        Secure Payments
                      </h6>
                      <p className="text-light fs-ms opacity-70 mb-0">
                        We posess SSL / Secure сertificate
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* <!-- Recent products grid--> */}
          <section className="container pb-5 mb-lg-3">
            {/* <!-- Heading--> */}
            <div className="d-flex flex-wrap justify-content-between align-items-center pt-1 border-bottom pb-4 mb-4">
              <h2 className="h3 mb-0 pt-3 me-2">The most recent releases</h2>
              <div className="pt-3">
                <select className="form-select me-2">
                  <option>All categories</option>
                  <option>Photos</option>
                  <option>Graphics</option>
                  <option>UI Design</option>
                  <option>Web Themes</option>
                  <option>Fonts</option>
                  <option>Add-Ons</option>
                </select>
              </div>
            </div>
            {/* <!-- Grid--> */}
            <div className="row pt-2 mx-n2">
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                {/* <!-- Product--> */}
                <div className="card product-card-alt">
                  <div className="product-thumb">
                    <button className="btn-wishlist btn-sm" type="button">
                      <i className="ci-heart"></i>
                    </button>
                    <div className="product-card-actions">
                      <a
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        href="marketplace-single.html"
                      >
                        <i className="ci-eye"></i>
                      </a>
                      <button
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        type="button"
                      >
                        <i className="ci-cart"></i>
                      </button>
                    </div>
                    <a
                      className="product-thumb-overlay"
                      href="marketplace-single.html"
                    ></a>
                    <img src="img/marketplace/products/01.jpg" alt="Product" />
                  </div>
                  <div className="card-body">
                    <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                      <div className="text-muted fs-xs me-1">
                        by{" "}
                        <a className="product-meta fw-medium" href="#">
                          Createx Std.{" "}
                        </a>
                        in{" "}
                        <a className="product-meta fw-medium" href="#">
                          UI Design
                        </a>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-half active"></i>
                        <i className="star-rating-icon ci-star"></i>
                      </div>
                    </div>
                    <h3 className="product-title fs-sm mb-2">
                      <a href="marketplace-single.html">
                        Square Style Mobile UI Kit (Sketch)
                      </a>
                    </h3>
                    <div className="d-flex flex-wrap justify-content-between align-items-center">
                      <div className="fs-sm me-2">
                        <i className="ci-download text-muted me-1"></i>153
                        <span className="fs-xs ms-1">Sales</span>
                      </div>
                      <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                        $24.<small>00</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                <div className="card product-card-alt">
                  <div className="product-thumb">
                    <button className="btn-wishlist btn-sm" type="button">
                      <i className="ci-heart"></i>
                    </button>
                    <div className="product-card-actions">
                      <a
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        href="marketplace-single.html"
                      >
                        <i className="ci-eye"></i>
                      </a>
                      <button
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        type="button"
                      >
                        <i className="ci-cart"></i>
                      </button>
                    </div>
                    <a
                      className="product-thumb-overlay"
                      href="marketplace-single.html"
                    ></a>
                    <img src="img/marketplace/products/04.jpg" alt="Product" />
                  </div>
                  <div className="card-body">
                    <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                      <div className="text-muted fs-xs me-1">
                        by{" "}
                        <a className="product-meta fw-medium" href="#">
                          Createx Std.{" "}
                        </a>
                        in{" "}
                        <a className="product-meta fw-medium" href="#">
                          Graphics
                        </a>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                      </div>
                    </div>
                    <h3 className="product-title fs-sm mb-2">
                      <a href="marketplace-single.html">
                        Flat-line E-Commerce Icons (AI)
                      </a>
                    </h3>
                    <div className="d-flex flex-wrap justify-content-between align-items-center">
                      <div className="fs-sm me-2">
                        <i className="ci-download text-muted me-1"></i>26
                        <span className="fs-xs ms-1">Sales</span>
                      </div>
                      <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                        $18.<small>00</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                <div className="card product-card-alt">
                  <div className="product-thumb">
                    <button className="btn-wishlist btn-sm" type="button">
                      <i className="ci-heart"></i>
                    </button>
                    <div className="product-card-actions">
                      <a
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        href="marketplace-single.html"
                      >
                        <i className="ci-eye"></i>
                      </a>
                      <button
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        type="button"
                      >
                        <i className="ci-cart"></i>
                      </button>
                    </div>
                    <a
                      className="product-thumb-overlay"
                      href="marketplace-single.html"
                    ></a>
                    <img src="img/marketplace/products/09.jpg" alt="Product" />
                  </div>
                  <div className="card-body">
                    <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                      <div className="text-muted fs-xs me-1">
                        by{" "}
                        <a className="product-meta fw-medium" href="#">
                          pixels
                        </a>
                        in{" "}
                        <a className="product-meta fw-medium" href="#">
                          UI Design
                        </a>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star"></i>
                      </div>
                    </div>
                    <h3 className="product-title fs-sm mb-2">
                      <a href="marketplace-single.html">
                        Isometric Device Mockups (PSD)
                      </a>
                    </h3>
                    <div className="d-flex flex-wrap justify-content-between align-items-center">
                      <div className="fs-sm me-2">
                        <i className="ci-download text-muted me-1"></i>36
                        <span className="fs-xs ms-1">Sales</span>
                      </div>
                      <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                        $16.<small>00</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                <div className="card product-card-alt">
                  <div className="product-thumb">
                    <button className="btn-wishlist btn-sm" type="button">
                      <i className="ci-heart"></i>
                    </button>
                    <div className="product-card-actions">
                      <a
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        href="marketplace-single.html"
                      >
                        <i className="ci-eye"></i>
                      </a>
                      <button
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        type="button"
                      >
                        <i className="ci-cart"></i>
                      </button>
                    </div>
                    <a
                      className="product-thumb-overlay"
                      href="marketplace-single.html"
                    ></a>
                    <img src="img/marketplace/products/10.jpg" alt="Product" />
                  </div>
                  <div className="card-body">
                    <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                      <div className="text-muted fs-xs me-1">
                        by{" "}
                        <a className="product-meta fw-medium" href="#">
                          theDesigner{" "}
                        </a>
                        in{" "}
                        <a className="product-meta fw-medium" href="#">
                          Graphics
                        </a>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star"></i>
                      </div>
                    </div>
                    <h3 className="product-title fs-sm mb-2">
                      <a href="marketplace-single.html">
                        Coffe Paper Cup Mockup
                      </a>
                    </h3>
                    <div className="d-flex flex-wrap justify-content-between align-items-center">
                      <div className="fs-sm me-2">
                        <i className="ci-download text-muted me-1"></i>57
                        <span className="fs-xs ms-1">Sales</span>
                      </div>
                      <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                        $10.<small>00</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                <div className="card product-card-alt">
                  <div className="product-thumb">
                    <button className="btn-wishlist btn-sm" type="button">
                      <i className="ci-heart"></i>
                    </button>
                    <div className="product-card-actions">
                      <a
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        href="marketplace-single.html"
                      >
                        <i className="ci-eye"></i>
                      </a>
                      <button
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        type="button"
                      >
                        <i className="ci-cart"></i>
                      </button>
                    </div>
                    <a
                      className="product-thumb-overlay"
                      href="marketplace-single.html"
                    ></a>
                    <img src="img/marketplace/products/06.jpg" alt="Product" />
                  </div>
                  <div className="card-body">
                    <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                      <div className="text-muted fs-xs me-1">
                        by{" "}
                        <a className="product-meta fw-medium" href="#">
                          Createx Std.{" "}
                        </a>
                        in{" "}
                        <a className="product-meta fw-medium" href="#">
                          Graphics
                        </a>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                      </div>
                    </div>
                    <h3 className="product-title fs-sm mb-2">
                      <a href="marketplace-single.html">
                        Travel &amp; Landmark Icon Pack (AI)
                      </a>
                    </h3>
                    <div className="d-flex flex-wrap justify-content-between align-items-center">
                      <div className="fs-sm me-2">
                        <i className="ci-download text-muted me-1"></i>21
                        <span className="fs-xs ms-1">Sales</span>
                      </div>
                      <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                        $17.<small>00</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                <div className="card product-card-alt">
                  <div className="product-thumb">
                    <button className="btn-wishlist btn-sm" type="button">
                      <i className="ci-heart"></i>
                    </button>
                    <div className="product-card-actions">
                      <a
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        href="marketplace-single.html"
                      >
                        <i className="ci-eye"></i>
                      </a>
                      <button
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        type="button"
                      >
                        <i className="ci-cart"></i>
                      </button>
                    </div>
                    <a
                      className="product-thumb-overlay"
                      href="marketplace-single.html"
                    ></a>
                    <img src="img/marketplace/products/05.jpg" alt="Product" />
                  </div>
                  <div className="card-body">
                    <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                      <div className="text-muted fs-xs me-1">
                        by{" "}
                        <a className="product-meta fw-medium" href="#">
                          Createx Std.{" "}
                        </a>
                        in{" "}
                        <a className="product-meta fw-medium" href="#">
                          UI Design
                        </a>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star"></i>
                      </div>
                    </div>
                    <h3 className="product-title fs-sm mb-2">
                      <a href="marketplace-single.html">
                        Minimal Mobile App UI Kit (Sketch)
                      </a>
                    </h3>
                    <div className="d-flex flex-wrap justify-content-between align-items-center">
                      <div className="fs-sm me-2">
                        <i className="ci-download text-muted me-1"></i>117
                        <span className="fs-xs ms-1">Sales</span>
                      </div>
                      <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                        $23.<small>00</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                <div className="card product-card-alt">
                  <div className="product-thumb">
                    <button className="btn-wishlist btn-sm" type="button">
                      <i className="ci-heart"></i>
                    </button>
                    <div className="product-card-actions">
                      <a
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        href="marketplace-single.html"
                      >
                        <i className="ci-eye"></i>
                      </a>
                      <button
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        type="button"
                      >
                        <i className="ci-cart"></i>
                      </button>
                    </div>
                    <a
                      className="product-thumb-overlay"
                      href="marketplace-single.html"
                    ></a>
                    <img src="img/marketplace/products/11.jpg" alt="Product" />
                  </div>
                  <div className="card-body">
                    <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                      <div className="text-muted fs-xs me-1">
                        by{" "}
                        <a className="product-meta fw-medium" href="#">
                          pixels
                        </a>
                        in{" "}
                        <a className="product-meta fw-medium" href="#">
                          Graphics
                        </a>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-half active"></i>
                        <i className="star-rating-icon ci-star"></i>
                        <i className="star-rating-icon ci-star"></i>
                      </div>
                    </div>
                    <h3 className="product-title fs-sm mb-2">
                      <a href="marketplace-single.html">
                        Printed T-Shirt Mockup (PSD)
                      </a>
                    </h3>
                    <div className="d-flex flex-wrap justify-content-between align-items-center">
                      <div className="fs-sm me-2">
                        <i className="ci-download text-muted me-1"></i>94
                        <span className="fs-xs ms-1">Sales</span>
                      </div>
                      <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                        $12.<small>00</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* <!-- Product--> */}
              <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                <div className="card product-card-alt">
                  <div className="product-thumb">
                    <button className="btn-wishlist btn-sm" type="button">
                      <i className="ci-heart"></i>
                    </button>
                    <div className="product-card-actions">
                      <a
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        href="marketplace-single.html"
                      >
                        <i className="ci-eye"></i>
                      </a>
                      <button
                        className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                        type="button"
                      >
                        <i className="ci-cart"></i>
                      </button>
                    </div>
                    <a
                      className="product-thumb-overlay"
                      href="marketplace-single.html"
                    ></a>
                    <img src="img/marketplace/products/12.jpg" alt="Product" />
                  </div>
                  <div className="card-body">
                    <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                      <div className="text-muted fs-xs me-1">
                        by{" "}
                        <a className="product-meta fw-medium" href="#">
                          pixels
                        </a>
                        in{" "}
                        <a className="product-meta fw-medium" href="#">
                          Graphics
                        </a>
                      </div>
                      <div className="star-rating">
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star-filled active"></i>
                        <i className="star-rating-icon ci-star"></i>
                      </div>
                    </div>
                    <h3 className="product-title fs-sm mb-2">
                      <a href="marketplace-single.html">
                        Corporate Branding Mockup (PSD)
                      </a>
                    </h3>
                    <div className="d-flex flex-wrap justify-content-between align-items-center">
                      <div className="fs-sm me-2">
                        <i className="ci-download text-muted me-1"></i>122
                        <span className="fs-xs ms-1">Sales</span>
                      </div>
                      <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                        $18.<small>00</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* <!-- More button--> */}
            <div className="text-center">
              <a
                className="btn btn-outline-accent"
                href="marketplace-category.html"
              >
                View more products<i className="ci-arrow-right fs-ms ms-1"></i>
              </a>
            </div>
          </section>
        </main>
      </div>
    </React.Fragment>
  );
};

export default Home;
